# Generated by Django 4.0.3 on 2022-03-05 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('f_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('profileImg', models.ImageField(blank=True, default='default.jpg', null=True, upload_to=user.models.profile_picture_path, verbose_name='Profile Picture')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
